-- ============================================================
-- P0 CONTACT - TABLE PRIVEE DE MESSAGES
-- A exécuter dans Supabase > SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS public.contact_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
        CHECK (char_length(name) BETWEEN 2 AND 100),
    email text NOT NULL
        CHECK (char_length(email) BETWEEN 3 AND 254),
    message text NOT NULL
        CHECK (char_length(message) BETWEEN 10 AND 5000),
    ip_hash text NOT NULL,
    status text NOT NULL DEFAULT 'new'
        CHECK (status IN ('new', 'read', 'replied', 'archived')),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contact_messages_created_at
ON public.contact_messages(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contact_messages_ip_created_at
ON public.contact_messages(ip_hash, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_contact_messages_email_created_at
ON public.contact_messages(email, created_at DESC);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- Le navigateur ne doit avoir AUCUN accès direct à cette table.
REVOKE ALL ON TABLE public.contact_messages FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.contact_messages_id_seq FROM anon, authenticated;

-- Le backend Next.js utilise une Supabase Secret key / service role.
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.contact_messages
TO service_role;

GRANT USAGE, SELECT
ON SEQUENCE public.contact_messages_id_seq
TO service_role;

-- Aucun CREATE POLICY volontairement :
-- anon/authenticated ne peuvent ni lire ni insérer directement.
