-- Sécurité administrateur et formulaire de contact.
-- À appliquer après le schéma historique de backup.sql.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;
grant select on table public.admin_users to authenticated;

drop policy if exists "Admin users can read their membership" on public.admin_users;
create policy "Admin users can read their membership"
on public.admin_users
for select
to authenticated
using ((select auth.uid()) = user_id);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated, service_role;

grant insert, update, delete on table public.projects to authenticated;
grant insert, update, delete on table public.certificates to authenticated;
grant insert, update, delete on table public.tech_stack to authenticated;
grant usage, select on sequence public.certificates_id_seq to authenticated;
grant usage, select on sequence public.tech_stack_id_seq to authenticated;

insert into storage.buckets (id, name, public)
values
  ('projects', 'projects', true),
  ('certificates', 'certificates', true),
  ('tech-stack', 'tech-stack', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public read portfolio assets" on storage.objects;
create policy "Public read portfolio assets"
on storage.objects
for select
to public
using (bucket_id in ('projects', 'certificates', 'tech-stack'));

drop policy if exists "Admin manage portfolio assets" on storage.objects;
create policy "Admin manage portfolio assets"
on storage.objects
for all
to authenticated
using (
  bucket_id in ('projects', 'certificates', 'tech-stack')
  and (select public.is_admin())
)
with check (
  bucket_id in ('projects', 'certificates', 'tech-stack')
  and (select public.is_admin())
);

-- Les contenus restent lisibles publiquement, mais seul un membre de
-- admin_users peut les créer, les modifier ou les supprimer depuis le client.
drop policy if exists "Admin manage projects" on public.projects;
create policy "Admin manage projects"
on public.projects
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admin manage certificates" on public.certificates;
create policy "Admin manage certificates"
on public.certificates
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admin manage tech stack" on public.tech_stack;
create policy "Admin manage tech stack"
on public.tech_stack
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admin manage comments" on public.comments;
create policy "Admin manage comments"
on public.comments
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 2 and 100),
  email text not null check (char_length(email) between 3 and 254),
  message text not null check (char_length(message) between 10 and 5000),
  ip_hash text not null,
  status text not null default 'new'
    check (status in ('new', 'read', 'replied', 'archived')),
  created_at timestamptz not null default now()
);

create index if not exists idx_contact_messages_created_at
on public.contact_messages(created_at desc);

create index if not exists idx_contact_messages_ip_created_at
on public.contact_messages(ip_hash, created_at desc);

create index if not exists idx_contact_messages_email_created_at
on public.contact_messages(email, created_at desc);

alter table public.contact_messages enable row level security;
revoke all on table public.contact_messages from anon, authenticated;
revoke all on sequence public.contact_messages_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.contact_messages to service_role;
grant usage, select on sequence public.contact_messages_id_seq to service_role;

create or replace function public.submit_contact_message(
  p_name text,
  p_email text,
  p_message text,
  p_ip_hash text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count bigint;
  inserted_id bigint;
begin
  -- Sérialise les soumissions d'une même IP anonymisée.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_ip_hash, 0)
  );

  select count(*)
  into recent_count
  from public.contact_messages
  where ip_hash = p_ip_hash
    and created_at >= now() - interval '15 minutes';

  if recent_count >= 3 then
    raise exception 'CONTACT_RATE_LIMIT' using errcode = 'P0001';
  end if;

  insert into public.contact_messages (name, email, message, ip_hash)
  values (p_name, p_email, p_message, p_ip_hash)
  returning id into inserted_id;

  return inserted_id;
end;
$$;

revoke all on function public.submit_contact_message(text, text, text, text)
from public, anon, authenticated;
grant execute on function public.submit_contact_message(text, text, text, text)
to service_role;

-- Après avoir créé votre compte dans Supabase Auth, accordez le rôle une fois :
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'votre-email@example.com';
