-- Applied to the portfolio project on 2026-09-13. Version matches remote history.
-- No existing comments, likes, contact messages or assets are changed.

create table if not exists public.public_request_attempts (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('comment', 'like')),
  ip_hash text not null check (ip_hash ~ '^[a-f0-9]{64}$'),
  created_at timestamptz not null default now()
);

create index if not exists idx_public_request_attempts_action_ip_created
on public.public_request_attempts (action, ip_hash, created_at desc);
create index if not exists idx_public_request_attempts_created
on public.public_request_attempts (created_at);

alter table public.public_request_attempts enable row level security;
revoke all on table public.public_request_attempts from anon, authenticated;
revoke all on sequence public.public_request_attempts_id_seq from anon, authenticated;
grant select, insert, delete on table public.public_request_attempts to service_role;
grant usage, select on sequence public.public_request_attempts_id_seq to service_role;

create or replace function public.reserve_public_request(p_action text, p_ip_hash text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  request_limit integer;
  recent_count bigint;
begin
  request_limit := case p_action when 'comment' then 3 when 'like' then 30 else null end;

  if request_limit is null or p_ip_hash is null or p_ip_hash !~ '^[a-f0-9]{64}$' then
    raise exception 'PUBLIC_REQUEST_INVALID' using errcode = '22023';
  end if;

  -- Serialize concurrent requests for this action and pseudonymous IP.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('portfolio-request:' || p_action || ':' || p_ip_hash, 0)
  );

  -- Only this new, temporary abuse-prevention table is cleaned up.
  -- Bound each cleanup so a request cannot trigger an unbounded maintenance job.
  delete from public.public_request_attempts
  where id in (
    select id from public.public_request_attempts
    where created_at < now() - interval '1 day'
    order by created_at
    limit 1000
  );

  select count(*) into recent_count
  from public.public_request_attempts
  where action = p_action and ip_hash = p_ip_hash
    and created_at >= now() - interval '15 minutes';

  if recent_count >= request_limit then
    raise exception 'PUBLIC_REQUEST_RATE_LIMIT' using errcode = 'P0001';
  end if;

  insert into public.public_request_attempts (action, ip_hash)
  values (p_action, p_ip_hash);
end;
$$;

revoke all on function public.reserve_public_request(text, text) from public, anon, authenticated;
grant execute on function public.reserve_public_request(text, text) to service_role;

-- Existing files were audited before choosing these limits. SVG logos are used.
update storage.buckets
set file_size_limit = 10485760,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
where id in ('projects', 'certificates');

update storage.buckets
set file_size_limit = 2097152,
    allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/svg+xml']
where id = 'tech-stack';

-- This Supabase event trigger is not an application RPC. Preserve the trigger.
do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    revoke execute on function public.rls_auto_enable() from public, anon, authenticated;
  end if;
end;
$$;
