-- Schéma initial du portfolio. Les migrations suivantes renforcent la sécurité.

create extension if not exists "pgcrypto";

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  title text not null,
  image_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  name text,
  comment text,
  image_url text,
  likes integer not null default 0,
  is_pinned boolean not null default false,
  replies jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  liked_by_admin boolean not null default false
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  live_url text,
  github_url text,
  technologies text[] not null default '{}'::text[],
  key_features text[] not null default '{}'::text[],
  image_url text,
  image_urls jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tech_stack (
  id bigint generated by default as identity primary key,
  name text not null,
  logo_url text,
  created_at timestamptz not null default now()
);

create index if not exists idx_projects_created_at on public.projects(created_at);
create index if not exists idx_comments_created_at on public.comments(created_at);

alter table public.projects enable row level security;
alter table public.comments enable row level security;
alter table public.certificates enable row level security;
alter table public.tech_stack enable row level security;

grant select on table public.projects, public.comments, public.certificates, public.tech_stack
to anon, authenticated;

drop policy if exists "Allow public read projects" on public.projects;
create policy "Allow public read projects" on public.projects for select to public using (true);

drop policy if exists "Allow public read comments" on public.comments;
create policy "Allow public read comments" on public.comments for select to public using (true);

drop policy if exists "Allow public read certificates" on public.certificates;
create policy "Allow public read certificates" on public.certificates for select to public using (true);

drop policy if exists "Allow public read tech_stack" on public.tech_stack;
create policy "Allow public read tech_stack" on public.tech_stack for select to public using (true);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_projects_updated_at on public.projects;
create trigger update_projects_updated_at
before update on public.projects
for each row execute function public.update_updated_at_column();
