-- Commentaires publics via fonctions atomiques ; administration via RLS.

create table if not exists public.comment_submissions (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_comment_submissions_ip_created_at
on public.comment_submissions(ip_hash, created_at desc);

alter table public.comment_submissions enable row level security;
revoke all on table public.comment_submissions from anon, authenticated;
revoke all on sequence public.comment_submissions_id_seq from anon, authenticated;
grant select, insert, delete on table public.comment_submissions to service_role;
grant usage, select on sequence public.comment_submissions_id_seq to service_role;

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  client_hash text not null,
  created_at timestamptz not null default now(),
  primary key (comment_id, client_hash)
);

alter table public.comment_likes enable row level security;
revoke all on table public.comment_likes from anon, authenticated;
grant select, insert, delete on table public.comment_likes to service_role;

-- L'ancien INSERT public permettait de contourner toutes les validations.
drop policy if exists "Allow public insert comments" on public.comments;
revoke insert, update, delete on table public.comments from anon;
grant select on table public.comments to anon, authenticated;
grant insert, update, delete on table public.comments to authenticated;
grant select, insert, update, delete on table public.comments to service_role;
grant usage, select on sequence public.comments_id_seq to service_role;

create or replace function public.submit_comment(
  p_name text,
  p_comment text,
  p_image_url text,
  p_ip_hash text
)
returns setof public.comments
language plpgsql
security definer
set search_path = ''
as $$
declare
  recent_count bigint;
  inserted_comment public.comments;
begin
  if char_length(trim(p_name)) not between 2 and 80
    or char_length(trim(p_comment)) not between 3 and 1000 then
    raise exception 'COMMENT_INVALID' using errcode = 'P0001';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_ip_hash, 0)
  );

  select count(*)
  into recent_count
  from public.comment_submissions
  where ip_hash = p_ip_hash
    and created_at >= now() - interval '15 minutes';

  if recent_count >= 3 then
    raise exception 'COMMENT_RATE_LIMIT' using errcode = 'P0001';
  end if;

  insert into public.comments (
    name,
    comment,
    image_url,
    likes,
    replies,
    is_pinned,
    liked_by_admin
  )
  values (
    trim(p_name),
    trim(p_comment),
    p_image_url,
    0,
    '[]'::jsonb,
    false,
    false
  )
  returning * into inserted_comment;

  insert into public.comment_submissions (ip_hash) values (p_ip_hash);
  return next inserted_comment;
end;
$$;

revoke all on function public.submit_comment(text, text, text, text)
from public, anon, authenticated;
grant execute on function public.submit_comment(text, text, text, text)
to service_role;

create or replace function public.like_comment_once(
  p_comment_id bigint,
  p_client_hash text
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  inserted_count integer;
  current_likes integer;
begin
  insert into public.comment_likes (comment_id, client_hash)
  values (p_comment_id, p_client_hash)
  on conflict do nothing;

  get diagnostics inserted_count = row_count;

  if inserted_count = 1 then
    update public.comments
    set likes = coalesce(likes, 0) + 1
    where id = p_comment_id
    returning likes into current_likes;
  else
    select coalesce(likes, 0)
    into current_likes
    from public.comments
    where id = p_comment_id;
  end if;

  if current_likes is null then
    raise exception 'COMMENT_NOT_FOUND' using errcode = 'P0002';
  end if;

  return current_likes;
end;
$$;

revoke all on function public.like_comment_once(bigint, text)
from public, anon, authenticated;
grant execute on function public.like_comment_once(bigint, text)
to service_role;

create or replace function public.append_admin_comment_reply(
  p_comment_id bigint,
  p_message text
)
returns setof public.comments
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_comment public.comments;
begin
  if not public.is_admin() then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  if char_length(trim(p_message)) not between 1 and 1000 then
    raise exception 'REPLY_INVALID' using errcode = 'P0001';
  end if;

  update public.comments
  set replies = coalesce(replies, '[]'::jsonb) || jsonb_build_array(
    jsonb_build_object(
      'username', 'Admin',
      'message', trim(p_message),
      'created_at', now()
    )
  )
  where id = p_comment_id
  returning * into updated_comment;

  return next updated_comment;
end;
$$;

revoke all on function public.append_admin_comment_reply(bigint, text)
from public, anon;
grant execute on function public.append_admin_comment_reply(bigint, text)
to authenticated, service_role;

create or replace function public.toggle_admin_comment_like(p_comment_id bigint)
returns setof public.comments
language plpgsql
security definer
set search_path = ''
as $$
declare
  updated_comment public.comments;
begin
  if not public.is_admin() then
    raise exception 'ADMIN_REQUIRED' using errcode = '42501';
  end if;

  update public.comments
  set
    liked_by_admin = not coalesce(liked_by_admin, false),
    likes = case
      when coalesce(liked_by_admin, false) then greatest(coalesce(likes, 0) - 1, 0)
      else coalesce(likes, 0) + 1
    end
  where id = p_comment_id
  returning * into updated_comment;

  return next updated_comment;
end;
$$;

revoke all on function public.toggle_admin_comment_like(bigint)
from public, anon;
grant execute on function public.toggle_admin_comment_like(bigint)
to authenticated, service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'comments',
  'comments',
  true,
  2000000,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public read comment images" on storage.objects;
create policy "Public read comment images"
on storage.objects
for select
to public
using (bucket_id = 'comments');
